/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.com.google.guava.guava)
    api(libs.org.apache.pdfbox.pdfbox)
    api(libs.org.apache.logging.log4j.log4j.core)
    api(libs.org.apache.logging.log4j.log4j.api)
    api(libs.org.eclipse.jetty.jetty.server)
    api(libs.org.eclipse.jetty.jetty.servlet)
    api(libs.com.google.code.gson.gson)
    api(libs.org.apache.poi.poi)
    api(libs.org.apache.poi.poi.ooxml)
    api(libs.com.squareup.moshi.moshi)
    api(libs.com.squareup.moshi.moshi.adapters)
    api(libs.com.squareup.okio.okio)
    api(libs.com.sparkjava.spark.core)
    api(libs.org.slf4j.slf4j.nop)
    api(libs.org.json.json)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
}

group = "org.example"
version = "1.0-SNAPSHOT"
description = "moshi"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
